### ISSUE TITLE
Support for list value instances

### ISSUE THREAD

**Issue by pfroud** [Mingun/kaitai_struct_model#14]
KSY file:
```yaml
meta:
  id: value_instance_list
instances:
  value_instance_list:
    value: "[0.1, 0.2]"
```

Compiled Java code:
```java
 public ArrayList<Double> valueInstanceList() { ... }
```

Right now, kaitai_struct_model creates a `SimpleNode` where the `value` is an ArrayList, because of this `isPresent` check:

https://github.com/Mingun/kaitai_struct_model/commit/f55d91130f091dc4fe16ad35b8a9c719af342ab7#diff-35a4962b04608dbbd0bbf57c37dd15b866476c46f96151f5d70c9cef4b21ac93R169

I am wondering if the `isPresent` check is still needed - if I comment it out, it looks like everything works correctly.
