### ISSUE TITLE
Add node types

### ISSUE THREAD

**Issue by pfroud** [Mingun/kaitai_struct_model#8]
I want to use kaitai_struct_model in my fork of [kaitai_struct_gui](https://github.com/kaitai-io/kaitai_struct_gui/) to make colored icons for different types of tree nodes. 

The idea is inspired by IDEs, for example this Java file:

```java
class MyClass {
  int myField;
  void myMethod() {}
  interface MyInterface {}
  enum MyEnum {}
}
```

Produces these trees in different IDEs:

![java navigation trees in different IDEs](https://user-images.githubusercontent.com/9056906/171726928-0f6203b5-bf48-47b8-9427-a74b53409cce.png)

Links to what the different icons mean in different IDEs:

* Can't find one for IntelliJ IDEA so here's [PyCharm](https://www.jetbrains.com/help/pycharm/symbols.html#file-types)
* [Eclipse IDE](https://help.eclipse.org/latest/index.jsp?topic=/org.eclipse.jdt.doc.user/reference/ref-icons.htm)
* [NetBeans IDE](https://docs.oracle.com/cd/E50453_01/doc.80/e50452/work_java_code.htm#r1c1-t5)

To change icons in a `JTree` it looks like we use a `TreeCellRenderer`, which is separate from a `TreeModel`. So I think the icons implementation can't be a part of the kaitai_struct_model project. But I want kaitai_struct_model to distinguish different types of entries so an external TreeCellRenderer can check the node types.

Here's a demonstration of colored icons from [my fork](https://github.com/pfroud/kaitai_struct_tree_model):

![colored icons in kaitai-struct tree](https://user-images.githubusercontent.com/9056906/171727007-1481a47a-ff43-43fd-856b-94e585ade997.png)

* Teal square is a `StructNode`
* Red circle is a `ListNode`
* Purple triangle is a `SimpleNode`

Here's the KSY file I am using:

```yaml
meta:
  id: test
seq:
  - id: sequential_item
    type: u1
  - id: enum_sequential_item
    type: u1
    enum: my_enum
  - id: my_array
    type: my_type
    repeat: expr
    repeat-expr: 2
  - id: the_rest
    size-eos: true
instances:
  my_instance:
    pos: 1
    type: u1
  my_value_instance:
    value: 1
enums:
  my_enum:
    1: first_enum_value
    2: second_enum_value
types:
  my_type:
    seq:
      - id: foo
        type: u1
      - id: bar
        type: u1        
```
Any suggestions for things to add to the test ksy file? I know it does not include params.

I can think of two dimensions for the icons:
1. Whether it is a sequential item or an instance
2. Data type (array, Struct, primitive, enum, ...)

What do you think?
